// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeApiUK053YtwgMMnRwbM8MGdOyVwfcLc',
    appId: '1:720159266790:web:dea8d7bb65970151bda827',
    messagingSenderId: '720159266790',
    projectId: 'tictok-tarin-nomad-abc',
    authDomain: 'tictok-tarin-nomad-abc.firebaseapp.com',
    storageBucket: 'tictok-tarin-nomad-abc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvp82025hlD0fVwuHABgiJz-h5lneOrog',
    appId: '1:720159266790:android:905f09dfcc20f77abda827',
    messagingSenderId: '720159266790',
    projectId: 'tictok-tarin-nomad-abc',
    storageBucket: 'tictok-tarin-nomad-abc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP8xwudsNWLjDL4AJkIjhM2ZgUCCzww6Y',
    appId: '1:720159266790:ios:ecf9d326efdecff9bda827',
    messagingSenderId: '720159266790',
    projectId: 'tictok-tarin-nomad-abc',
    storageBucket: 'tictok-tarin-nomad-abc.appspot.com',
    iosBundleId: 'com.example.tictokclone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeApiUK053YtwgMMnRwbM8MGdOyVwfcLc',
    appId: '1:720159266790:web:071800ecdb003925bda827',
    messagingSenderId: '720159266790',
    projectId: 'tictok-tarin-nomad-abc',
    authDomain: 'tictok-tarin-nomad-abc.firebaseapp.com',
    storageBucket: 'tictok-tarin-nomad-abc.appspot.com',
  );

}